apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: bpa-trigger-runner
  annotations:
    scenarios.ai.sap.com/name: "BPA Orchestrator"
    executables.ai.sap.com/name: "Trigger Runner"
  labels:
    scenarios.ai.sap.com/id: "bpa-orchestrator"
    executables.ai.sap.com/id: "trigger-runner"
    ai.sap.com/version: "1.0"
spec:
 # imagePullSecrets:
 #  - name: credstutorialrepo        # your Docker Registry Secret name
  entrypoint: run
  templates:
    - name: run
      inputs:
        parameters:
          - name: excel_url
            default: ""
      container:
        image: docker.io/teenav1986/bpa-trigger-runner:01
        command: ["/bin/sh","-c"]
        args:
          - "python /app/main.py --excel-url '{{inputs.parameters.excel_url}}'"
        env:
          - name: BPA_MAP_JSON
            valueFrom:
              secretKeyRef:
                name: bpa-triggers-map   # Generic Secret name
                key: bpa_map_json
