apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: bpa-trigger-runner
  annotations:
    scenarios.ai.sap.com/name: "BPA Orchestrator"
    executables.ai.sap.com/name: "Trigger Runner"
    ai.sap.com/version: "2.0"
spec:
  imagePullSecrets:
    - name: docker-secret
  entrypoint: run
  templates:
    - name: run
      inputs:
        parameters:
          - name: excel_url
            default: ""
      container:
        image: docker.io/teenav1986/bpa-trigger-runner:02
        command: ["/bin/sh","-c"]
        args:
          - "python /app/main.py --excel-url '{{inputs.parameters.excel_url}}'"
        env:
          - name: BPA_MAP_JSON
            valueFrom:
              secretKeyRef:
                name: bpa-triggers-map    # <-- the Generic Secret you just created
                key: bpa_map_json         # <-- the single key that holds the whole JSON
